import { MigrationInterface, QueryRunner } from 'typeorm';

export class UpdateTable0011775990889313 implements MigrationInterface {
  name = 'UpdateTable0011775990889313';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_goods\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`id\` int NOT NULL AUTO_INCREMENT COMMENT 'ID', \`created_at\` datetime NULL COMMENT '创建时间', \`goods_id\` int NULL COMMENT '电商平台商品ID' DEFAULT '0', \`goods_name\` varchar(255) NULL COMMENT '商品名称' DEFAULT '', \`goods_quantity\` int NULL COMMENT '商品数量' DEFAULT '0', \`goods_reserve_quantity\` int NULL COMMENT '商品预留数量' DEFAULT '0', \`image_url\` varchar(255) NULL COMMENT '商品图片URL' DEFAULT '', \`is_more_sku\` tinyint NULL COMMENT '是否有多SKU' DEFAULT 0, \`is_onsale\` tinyint NULL COMMENT '是否上架' DEFAULT 0, \`outer_goods_id\` varchar(255) NULL COMMENT '外部商品ID' DEFAULT '', \`thumb_url\` varchar(255) NULL COMMENT '商品缩略图URL' DEFAULT '', \`mid\` int NULL COMMENT 'MID' DEFAULT '0', \`dept_id\` int NULL COMMENT '部门ID' DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB COMMENT="电商平台商品"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_sku\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'ID', \`is_sku_onsale\` tinyint NULL COMMENT '是否上架' DEFAULT 0, \`outer_id\` varchar(255) NULL COMMENT '外部ID' DEFAULT '', \`reserve_quantity\` int NULL COMMENT '预留数量' DEFAULT '0', \`sku_id\` int NULL COMMENT 'SKU ID' DEFAULT '0', \`sku_quantity\` int NULL COMMENT 'SKU数量' DEFAULT '0', \`spec\` varchar(255) NULL COMMENT '规格' DEFAULT '', \`goods_id\` int NULL COMMENT 'ID', PRIMARY KEY (\`id\`)) ENGINE=InnoDB COMMENT="电商平台SKU"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_spec\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'ID', \`parent_id\` int NULL COMMENT '父ID' DEFAULT '0', \`parent_name\` varchar(255) NULL COMMENT '父名称' DEFAULT '', \`spec_id\` int NULL COMMENT '规格ID' DEFAULT '0', \`spec_name\` varchar(255) NULL COMMENT '规格名称' DEFAULT '', \`spec_note\` varchar(255) NULL COMMENT '规格备注' DEFAULT '', \`sku_id\` int NULL COMMENT 'ID', PRIMARY KEY (\`id\`)) ENGINE=InnoDB COMMENT="电商平台规格"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_shop\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`shop_id\` int NOT NULL AUTO_INCREMENT COMMENT '店铺ID', \`shop_name\` varchar(255) NULL COMMENT '店铺名称' DEFAULT '', \`platform_type\` enum ('100', '200', '300', '400', '500') NOT NULL COMMENT '平台类型', \`token\` varchar(255) NULL COMMENT 'token' DEFAULT '', \`mid\` int NULL COMMENT 'mid', \`expires_time\` datetime NULL COMMENT 'token过期时间', \`user_name\` varchar(255) NULL COMMENT '用户名' DEFAULT '', \`mall_id\` int NULL COMMENT '商城ID', \`shop_code\` varchar(255) NULL COMMENT '店铺编码' DEFAULT '', \`dept_id\` int NULL COMMENT '部门ID', PRIMARY KEY (\`shop_id\`)) ENGINE=InnoDB COMMENT="电商平台店铺"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_refund\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`id\` int NOT NULL AUTO_INCREMENT COMMENT '售后ID', \`after_sale_reason\` varchar(255) NULL COMMENT '售后原因' DEFAULT '', \`after_sales_status\` int NULL COMMENT '售后状态' DEFAULT '0', \`after_sales_type\` int NULL COMMENT '售后类型' DEFAULT '0', \`confirm_time\` datetime NULL COMMENT '确认时间', \`created_time\` datetime NULL COMMENT '创建时间', \`discount_amount\` decimal(10,2) NULL COMMENT '优惠金额' DEFAULT '0.00', \`dispute_refund_status\` int NULL COMMENT '争议退款状态' DEFAULT '0', \`good_image\` varchar(255) NULL COMMENT '商品图片' DEFAULT '', \`goods_id\` bigint NULL COMMENT '商品ID' DEFAULT '0', \`goods_name\` varchar(255) NULL COMMENT '商品名称' DEFAULT '', \`goods_number\` int NULL COMMENT '商品数量' DEFAULT '0', \`goods_price\` decimal(10,2) NULL COMMENT '商品价格' DEFAULT '0.00', \`platform_after_sales_id\` int NULL COMMENT '平台售后ID' DEFAULT '0', \`order_amount\` decimal(10,2) NULL COMMENT '订单金额' DEFAULT '0.00', \`order_sn\` varchar(255) NULL COMMENT '订单号' DEFAULT '', \`outer_goods_id\` varchar(255) NULL COMMENT '外部商品ID' DEFAULT '', \`outer_id\` varchar(255) NULL COMMENT '外部ID' DEFAULT '', \`refund_amount\` decimal(10,2) NULL COMMENT '退款金额' DEFAULT '0.00', \`refund_operator_role\` int NULL COMMENT '退款操作人角色' DEFAULT '0', \`shipping_name\` varchar(255) NULL COMMENT '物流公司名称' DEFAULT '', \`sku_id\` varchar(50) NULL COMMENT 'SKU ID' DEFAULT '', \`speed_refund_flag\` int NULL COMMENT '极速退款标记' DEFAULT '0', \`speed_refund_status\` varchar(50) NULL COMMENT '极速退款状态' DEFAULT '', \`tracking_number\` varchar(50) NULL COMMENT '物流单号' DEFAULT '', \`updated_time\` datetime NULL COMMENT '更新时间', \`user_shipping_status\` varchar(10) NULL COMMENT '用户寄件状态' DEFAULT '', \`mid\` int NULL COMMENT 'MID' DEFAULT '0', \`dept_id\` int NULL COMMENT '部门ID' DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB COMMENT="电商平台售后"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_order\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`pt_order_id\` int NOT NULL AUTO_INCREMENT COMMENT '订单ID', \`receiver_name\` varchar(255) NULL COMMENT '收货人姓名' DEFAULT '', \`receiver_phone\` varchar(255) NULL COMMENT '收货人电话' DEFAULT '', \`province\` varchar(255) NULL COMMENT '省份' DEFAULT '', \`city\` varchar(255) NULL COMMENT '城市' DEFAULT '', \`town\` varchar(255) NULL COMMENT '乡镇' DEFAULT '', \`receiver_address\` varchar(255) NULL COMMENT '收货人地址' DEFAULT '', \`order_sn\` varchar(255) NULL COMMENT '订单号' DEFAULT '', \`goods_name\` varchar(255) NULL COMMENT '商品名称' DEFAULT '', \`goods_img\` varchar(255) NULL COMMENT '商品图片' DEFAULT '', \`goods_spec\` varchar(255) NULL COMMENT '商品规格' DEFAULT '', \`goods_price\` decimal(10,2) NULL COMMENT '商品价格' DEFAULT '0.00', \`goods_id\` varchar(255) NULL COMMENT '商品ID' DEFAULT '', \`sku_id\` varchar(255) NULL COMMENT 'SKU ID' DEFAULT '', \`is_pre_sale\` tinyint NULL COMMENT '是否预售' DEFAULT 0, \`last_ship_time\` datetime NULL COMMENT '最后发货时间', \`confirm_time\` datetime NULL COMMENT '确认时间', \`remark\` varchar(255) NULL COMMENT '备注' DEFAULT '', \`goods_count\` int NULL COMMENT '商品数量' DEFAULT '0', \`pay_amount\` decimal(10,2) NULL COMMENT '支付金额' DEFAULT '0.00', \`order_status\` enum ('1', '2', '3', '5') NULL COMMENT '订单状态' DEFAULT '1', \`refund_status\` enum ('1', '2', '3', '4', '5') NULL COMMENT '退款状态' DEFAULT '1', \`remark_tag\` int NULL COMMENT '备注标签' DEFAULT '0', \`remark_tag_name\` varchar(255) NULL COMMENT '备注标签名称' DEFAULT '', \`receiver_name_encrypt\` varchar(255) NULL COMMENT '收货人姓名加密' DEFAULT '', \`receiver_phone_encrypt\` varchar(255) NULL COMMENT '收货人电话加密' DEFAULT '', \`receiver_address_encrypt\` varchar(255) NULL COMMENT '收货人地址加密' DEFAULT '', \`open_address_id\` varchar(255) NULL COMMENT '开户地址ID' DEFAULT '', \`open_address_id_2\` varchar(255) NULL COMMENT '开户地址ID2' DEFAULT '', \`town_id\` int NULL COMMENT '乡镇ID' DEFAULT '0', \`outer_id\` varchar(255) NULL COMMENT '外部ID' DEFAULT '', \`outer_goods_id\` varchar(255) NULL COMMENT '外部商品ID' DEFAULT '', \`mid\` int NULL COMMENT 'MID' DEFAULT '0', \`dept_id\` int NULL COMMENT '部门ID' DEFAULT '0', PRIMARY KEY (\`pt_order_id\`)) ENGINE=InnoDB COMMENT="电商平台订单"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_order_goodsInfo\` (\`pt_order_goods_info_id\` int NOT NULL AUTO_INCREMENT COMMENT '订单商品信息ID', \`goods_count\` int NULL COMMENT '商品数量' DEFAULT '0', \`goods_name\` varchar(255) NULL COMMENT '商品名称' DEFAULT '', \`goods_img\` varchar(255) NULL COMMENT '商品图片' DEFAULT '', \`goods_spec\` varchar(255) NULL COMMENT '商品规格' DEFAULT '', \`goods_price\` decimal(10,2) NULL COMMENT '商品价格' DEFAULT '0.00', \`goods_id\` varchar(255) NULL COMMENT '商品ID' DEFAULT '', \`sku_id\` varchar(255) NULL COMMENT 'SKU ID' DEFAULT '', \`outer_id\` varchar(255) NULL COMMENT '外部ID' DEFAULT '', \`outer_goods_id\` varchar(255) NULL COMMENT '外部商品ID' DEFAULT '', \`ptOrderPtOrderId\` int NULL COMMENT '订单ID', PRIMARY KEY (\`pt_order_goods_info_id\`)) ENGINE=InnoDB COMMENT="电商平台订单商品信息"`,
    );
    await queryRunner.query(
      `ALTER TABLE \`e_commerce_platform_sku\` ADD CONSTRAINT \`FK_3b35d982aa8bbae4afce973508e\` FOREIGN KEY (\`goods_id\`) REFERENCES \`e_commerce_platform_goods\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`e_commerce_platform_spec\` ADD CONSTRAINT \`FK_298068f6a1a25ef0b81fdc65a20\` FOREIGN KEY (\`sku_id\`) REFERENCES \`e_commerce_platform_sku\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`e_commerce_platform_order_goodsInfo\` ADD CONSTRAINT \`FK_deb30e13848004b8855fe97b501\` FOREIGN KEY (\`ptOrderPtOrderId\`) REFERENCES \`e_commerce_platform_order\`(\`pt_order_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE \`e_commerce_platform_order_goodsInfo\` DROP FOREIGN KEY \`FK_deb30e13848004b8855fe97b501\``);
    await queryRunner.query(`ALTER TABLE \`e_commerce_platform_spec\` DROP FOREIGN KEY \`FK_298068f6a1a25ef0b81fdc65a20\``);
    await queryRunner.query(`ALTER TABLE \`e_commerce_platform_sku\` DROP FOREIGN KEY \`FK_3b35d982aa8bbae4afce973508e\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_order_goodsInfo\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_order\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_refund\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_shop\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_spec\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_sku\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_goods\``);
  }
}
