import { MigrationInterface, QueryRunner } from 'typeorm';

export class UpdateTable0011776151365304 implements MigrationInterface {
  name = 'UpdateTable0011776151365304';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `CREATE TABLE \`sys_upload\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`upload_id\` varchar(255) NOT NULL COMMENT '任务Id', \`size\` int NOT NULL COMMENT '文件大小', \`file_name\` varchar(255) NOT NULL COMMENT '文件路径', \`new_file_name\` varchar(255) NOT NULL COMMENT '文件名', \`url\` varchar(255) NOT NULL COMMENT '文件地址', \`dept_id\` int NULL COMMENT '部门ID', \`ext\` varchar(255) NULL COMMENT '拓展名', \`status\` char(1) NOT NULL COMMENT '状态' DEFAULT '0', PRIMARY KEY (\`upload_id\`)) ENGINE=InnoDB COMMENT="文件上传记录"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_user_role\` (\`user_id\` int NOT NULL COMMENT '用户ID', \`role_id\` int NOT NULL COMMENT '角色ID', \`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`dept_id\` int NULL COMMENT '部门ID', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', PRIMARY KEY (\`user_id\`, \`role_id\`)) ENGINE=InnoDB COMMENT="用户和角色关联表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_user\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`user_id\` int NOT NULL AUTO_INCREMENT COMMENT '用户ID', \`dept_id\` int NULL COMMENT '部门ID', \`user_name\` varchar(30) NOT NULL COMMENT '用户账号', \`nick_name\` varchar(30) NOT NULL COMMENT '用户昵称', \`user_type\` varchar(2) NOT NULL COMMENT '用户类型' DEFAULT '00', \`email\` varchar(50) NOT NULL COMMENT '邮箱' DEFAULT '', \`phonenumber\` varchar(11) NOT NULL COMMENT '手机号码' DEFAULT '', \`sex\` char(1) NOT NULL COMMENT '性别' DEFAULT '0', \`avatar\` varchar(255) NOT NULL COMMENT '头像地址' DEFAULT '', \`password\` varchar(200) NOT NULL COMMENT '用户登录密码' DEFAULT '', \`login_ip\` varchar(128) NOT NULL COMMENT '最后登录IP' DEFAULT '', \`login_date\` timestamp NULL COMMENT '最后登录时间', \`status\` char(1) NOT NULL COMMENT '状态' DEFAULT '0', PRIMARY KEY (\`user_id\`)) ENGINE=InnoDB COMMENT="用户信息表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`gen_table\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`table_id\` int NOT NULL AUTO_INCREMENT COMMENT '编号', \`table_name\` varchar(200) NOT NULL COMMENT '表名称' DEFAULT '', \`table_comment\` varchar(500) NOT NULL COMMENT '表描述' DEFAULT '', \`sub_table_name\` varchar(64) NULL COMMENT '关联子表的表名', \`sub_table_fk_name\` varchar(64) NULL COMMENT '子表关联的外键名', \`class_name\` varchar(100) NOT NULL COMMENT '实体类名称' DEFAULT '', \`tpl_category\` varchar(200) NOT NULL COMMENT '使用的模板（crud单表操作 tree树表操作）' DEFAULT 'crud', \`tpl_web_type\` varchar(30) NOT NULL COMMENT '前端模板类型（element-ui模版 element-plus模版）' DEFAULT 'element-plus', \`package_name\` varchar(100) NOT NULL COMMENT '生成包路径', \`module_name\` varchar(30) NOT NULL COMMENT '生成模块名', \`business_name\` varchar(30) NOT NULL COMMENT '生成业务名', \`function_name\` varchar(50) NOT NULL COMMENT '生成功能名', \`function_author\` varchar(50) NOT NULL COMMENT '生成功能作者', \`gen_type\` char(1) NOT NULL COMMENT '生成代码方式（0zip压缩包 1自定义路径）' DEFAULT '0', \`gen_path\` varchar(200) NOT NULL COMMENT '生成路径（不填默认项目路径）' DEFAULT '/', \`options\` varchar(1000) NOT NULL COMMENT '其它生成选项' DEFAULT '', \`dept_id\` int NULL COMMENT '部门ID', PRIMARY KEY (\`table_id\`)) ENGINE=InnoDB COMMENT="代码生成业务表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_user_post\` (\`user_id\` int NOT NULL COMMENT '用户ID', \`post_id\` int NOT NULL COMMENT '岗位ID', \`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`dept_id\` int NULL COMMENT '部门ID', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', PRIMARY KEY (\`user_id\`, \`post_id\`)) ENGINE=InnoDB COMMENT="用户与岗位关联表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`gen_table_column\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`column_id\` int NOT NULL AUTO_INCREMENT COMMENT '编号', \`table_id\` int NOT NULL COMMENT '归属表编号', \`column_name\` varchar(200) NOT NULL COMMENT '列名称', \`column_comment\` varchar(500) NOT NULL COMMENT '列描述', \`column_type\` varchar(100) NOT NULL COMMENT '列类型', \`java_type\` varchar(500) NOT NULL COMMENT 'JAVA类型', \`java_field\` varchar(200) NOT NULL COMMENT 'JAVA字段名', \`is_pk\` char(1) NOT NULL COMMENT '是否主键（1是）' DEFAULT '0', \`is_increment\` char(1) NOT NULL COMMENT '是否自增（1是）' DEFAULT '0', \`is_required\` char(1) NOT NULL COMMENT '是否必填（1是）' DEFAULT '0', \`is_insert\` char(1) NOT NULL COMMENT '是否为插入字段（1是）' DEFAULT '0', \`is_edit\` char(1) NULL COMMENT '是否编辑字段（1是）' DEFAULT '0', \`is_list\` char(1) NULL COMMENT '是否列表字段（1是）' DEFAULT '0', \`is_query\` char(1) NULL COMMENT '是否查询字段（1是）' DEFAULT '1', \`query_type\` varchar(200) NOT NULL COMMENT '查询方式（等于、不等于、大于、小于、范围）' DEFAULT 'EQ', \`html_type\` varchar(200) NOT NULL COMMENT '显示类型（文本框、文本域、下拉框、复选框、单选框、日期控件）' DEFAULT '', \`dict_type\` varchar(200) NOT NULL COMMENT '字典类型' DEFAULT '', \`column_default\` varchar(200) NULL COMMENT '默认值', \`sort\` int NOT NULL COMMENT '排序', \`dept_id\` int NULL COMMENT '部门ID', PRIMARY KEY (\`column_id\`)) ENGINE=InnoDB COMMENT="代码生成业务表字段"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_express\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`express_id\` int NOT NULL AUTO_INCREMENT COMMENT '快递公司ID', \`express_name\` varchar(255) NOT NULL COMMENT '快递公司名称', \`express_code\` varchar(255) NOT NULL COMMENT '物流公司代码 (快递100)', \`wx_code\` varchar(255) NOT NULL COMMENT '物流公司代码（微信小程序）', \`dy_express_code\` varchar(255) NOT NULL COMMENT '抖音物流公司代码（抖音商城）', \`sort\` int NOT NULL COMMENT '排序' DEFAULT '0', PRIMARY KEY (\`express_id\`)) ENGINE=InnoDB COMMENT="快递公司表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_shipping_template_rule\` (\`rule_id\` int NOT NULL AUTO_INCREMENT COMMENT '规则ID', \`city_ids\` json NOT NULL COMMENT '城市ID列表', \`first_weight\` decimal(10,2) NOT NULL COMMENT '首重', \`first_weight_price\` decimal(10,2) NOT NULL COMMENT '首重价格', \`additional_weight\` decimal(10,2) NOT NULL COMMENT '续重', \`additional_weight_price\` decimal(10,2) NOT NULL COMMENT '续重价格', \`is_remote\` tinyint NOT NULL COMMENT '是否偏远地区模板' DEFAULT 0, \`shipping_template_id\` int NULL COMMENT '模板ID', PRIMARY KEY (\`rule_id\`)) ENGINE=InnoDB COMMENT="运费模板规则"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_shipping_template\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`shipping_template_id\` int NOT NULL AUTO_INCREMENT COMMENT '模板ID', \`shipping_template_name\` varchar(255) NOT NULL COMMENT '模板名称', \`fee_type\` enum ('weight') NOT NULL COMMENT '计费方式', \`sort\` int NOT NULL COMMENT '排序值' DEFAULT '0', \`dept_id\` int NULL COMMENT '部门ID', \`express_id\` int NULL COMMENT '快递公司ID', PRIMARY KEY (\`shipping_template_id\`)) ENGINE=InnoDB COMMENT="运费模板"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_role\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`role_id\` int NOT NULL AUTO_INCREMENT COMMENT '角色ID', \`role_name\` varchar(30) NOT NULL COMMENT '角色名称', \`role_sort\` int NOT NULL COMMENT '显示顺序' DEFAULT '0', \`role_key\` varchar(100) NOT NULL COMMENT '角色权限字符串', \`dept_id\` int NULL COMMENT '部门ID', \`data_scope\` char(1) NOT NULL COMMENT '数据范围' DEFAULT '1', \`menu_check_strictly\` tinyint NOT NULL COMMENT '菜单树选择项是否关联显示' DEFAULT 0, \`dept_check_strictly\` tinyint NOT NULL COMMENT '部门树选择项是否关联显示' DEFAULT 0, \`status\` char(1) NOT NULL COMMENT '状态' DEFAULT '0', \`remark\` varchar(500) NOT NULL COMMENT '备注', PRIMARY KEY (\`role_id\`)) ENGINE=InnoDB COMMENT="角色信息表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_role_dept\` (\`role_id\` int NOT NULL COMMENT '角色ID' DEFAULT '0', \`dept_id\` int NOT NULL COMMENT '部门ID' DEFAULT '0', \`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', PRIMARY KEY (\`role_id\`, \`dept_id\`)) ENGINE=InnoDB COMMENT="角色和部门关联表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_role_menu\` (\`role_id\` int NOT NULL COMMENT '角色ID' DEFAULT '0', \`menu_id\` int NOT NULL COMMENT '菜单ID' DEFAULT '0', \`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`dept_id\` int NULL COMMENT '部门ID', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', PRIMARY KEY (\`role_id\`, \`menu_id\`)) ENGINE=InnoDB COMMENT="角色和菜单关联表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_region\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`id\` int NOT NULL AUTO_INCREMENT COMMENT '地区ID', \`pid\` int NULL COMMENT '父ID', \`shortname\` varchar(100) NULL COMMENT '简称', \`name\` varchar(100) NULL COMMENT '名称', \`merger_name\` varchar(100) NULL COMMENT '全称', \`level\` tinyint NULL COMMENT '层级 1 2 3 省市区县' DEFAULT '0', \`pinyin\` varchar(100) NULL COMMENT '拼音', \`code\` varchar(100) NULL COMMENT '长途区号', \`zip_code\` varchar(100) NULL COMMENT '邮编', \`first\` varchar(50) NULL COMMENT '首字母', \`lng\` varchar(100) NULL COMMENT '经度', \`lat\` varchar(100) NULL COMMENT '纬度', \`sort\` int NULL COMMENT '排序' DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB COMMENT="地区表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_post\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`post_id\` int NOT NULL AUTO_INCREMENT COMMENT '岗位ID', \`post_code\` varchar(64) NOT NULL COMMENT '岗位编码', \`post_name\` varchar(50) NOT NULL COMMENT '岗位名称', \`post_sort\` int NOT NULL COMMENT '显示顺序' DEFAULT '0', \`dept_id\` int NULL COMMENT '部门ID', \`status\` char(1) NOT NULL COMMENT '状态' DEFAULT '0', \`remark\` varchar(500) NOT NULL COMMENT '备注', PRIMARY KEY (\`post_id\`)) ENGINE=InnoDB COMMENT="岗位信息表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_notice\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`notice_id\` int NOT NULL AUTO_INCREMENT COMMENT '公告ID', \`notice_title\` varchar(50) NOT NULL COMMENT '公告标题' DEFAULT '', \`notice_type\` char(1) NOT NULL COMMENT '公告类型', \`notice_content\` longtext NULL COMMENT '公告内容', \`dept_id\` int NULL COMMENT '部门ID', PRIMARY KEY (\`notice_id\`)) ENGINE=InnoDB COMMENT="通知公告表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_menu\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`menu_id\` int NOT NULL AUTO_INCREMENT COMMENT '菜单ID', \`menu_name\` varchar(50) NOT NULL COMMENT '菜单名称', \`parent_id\` int NOT NULL COMMENT '父菜单ID', \`order_num\` int NOT NULL COMMENT '显示顺序' DEFAULT '0', \`path\` varchar(200) NOT NULL COMMENT '路由地址' DEFAULT '', \`component\` varchar(255) NULL COMMENT '组件路径', \`query\` varchar(255) NOT NULL COMMENT '路由参数' DEFAULT '', \`is_frame\` char NOT NULL COMMENT '是否为外链' DEFAULT '1', \`is_cache\` char NOT NULL COMMENT '是否缓存' DEFAULT '0', \`visible\` char NOT NULL COMMENT '是否显示' DEFAULT '0', \`menu_type\` char(1) NOT NULL COMMENT '菜单类型' DEFAULT 'M', \`perms\` varchar(100) NOT NULL COMMENT '权限标识' DEFAULT '', \`icon\` varchar(100) NOT NULL COMMENT '菜单图标' DEFAULT '', \`dept_id\` int NULL COMMENT '部门ID', \`status\` char(1) NOT NULL COMMENT '状态' DEFAULT '0', PRIMARY KEY (\`menu_id\`)) ENGINE=InnoDB COMMENT="菜单权限表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_dict_data\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`dict_code\` int NOT NULL AUTO_INCREMENT COMMENT '字典主键', \`dict_sort\` int NOT NULL COMMENT '字典排序' DEFAULT '0', \`dict_label\` varchar(100) NOT NULL COMMENT '字典标签', \`dict_value\` varchar(100) NOT NULL COMMENT '字典键值', \`dict_type\` varchar(100) NOT NULL COMMENT '字典类型', \`css_class\` varchar(100) NOT NULL COMMENT '样式属性' DEFAULT '', \`list_class\` varchar(100) NOT NULL COMMENT '表格回显样式', \`is_default\` char(1) NOT NULL COMMENT '是否默认' DEFAULT 'N', \`status\` char(1) NOT NULL COMMENT '状态' DEFAULT '0', \`remark\` varchar(500) NULL COMMENT '备注', \`dept_id\` int NULL COMMENT '部门ID', PRIMARY KEY (\`dict_code\`)) ENGINE=InnoDB COMMENT="字典数据表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_dict_type\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`dict_id\` int NOT NULL AUTO_INCREMENT COMMENT '字典主键', \`dict_name\` varchar(100) NOT NULL COMMENT '字典名称', \`dict_type\` varchar(100) NOT NULL COMMENT '字典类型', \`dept_id\` int NULL COMMENT '部门ID', \`status\` char(1) NOT NULL COMMENT '状态' DEFAULT '0', \`remark\` varchar(500) NOT NULL COMMENT '备注', UNIQUE INDEX \`IDX_f4e4273658733a3bbe6a2479bf\` (\`dict_type\`), PRIMARY KEY (\`dict_id\`)) ENGINE=InnoDB COMMENT="字典类型表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_dept\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`dept_id\` int NOT NULL AUTO_INCREMENT COMMENT '部门ID', \`parent_id\` int NOT NULL COMMENT '父部门ID' DEFAULT '0', \`ancestors\` varchar(50) NOT NULL COMMENT '祖级列表' DEFAULT '0', \`dept_name\` varchar(30) NOT NULL COMMENT '部门名称', \`order_num\` int NOT NULL COMMENT '显示顺序' DEFAULT '0', \`leader\` varchar(20) NOT NULL COMMENT '负责人', \`phone\` varchar(11) NOT NULL COMMENT '联系电话' DEFAULT '', \`email\` varchar(50) NOT NULL COMMENT '邮箱' DEFAULT '', \`status\` char(1) NOT NULL COMMENT '状态' DEFAULT '0', PRIMARY KEY (\`dept_id\`)) ENGINE=InnoDB COMMENT="部门表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_config\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`config_id\` int NOT NULL AUTO_INCREMENT COMMENT '参数主键', \`config_name\` varchar(100) NOT NULL COMMENT '参数名称' DEFAULT '', \`config_key\` varchar(100) NOT NULL COMMENT '参数键名' DEFAULT '', \`config_value\` varchar(500) NOT NULL COMMENT '参数键值' DEFAULT '', \`config_type\` char(1) NOT NULL COMMENT '系统内置' DEFAULT 'N', \`dept_id\` int NULL COMMENT '部门ID', PRIMARY KEY (\`config_id\`)) ENGINE=InnoDB COMMENT="参数配置表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_oper_log\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`dept_id\` int NULL COMMENT '部门ID', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`oper_id\` int NOT NULL AUTO_INCREMENT COMMENT '日志主键', \`title\` varchar(50) NOT NULL COMMENT '模块标题' DEFAULT '', \`business_type\` int NOT NULL COMMENT '业务类型' DEFAULT '0', \`method\` varchar(100) NOT NULL COMMENT '方法名称' DEFAULT '', \`request_method\` varchar(10) NOT NULL COMMENT '请求方式' DEFAULT '', \`operator_type\` varchar(255) NOT NULL COMMENT '操作类别' DEFAULT '0', \`oper_name\` varchar(50) NOT NULL COMMENT '操作人员' DEFAULT '', \`dept_name\` varchar(50) NOT NULL COMMENT '部门名称' DEFAULT '', \`oper_url\` varchar(255) NOT NULL COMMENT '请求URL' DEFAULT '', \`oper_ip\` varchar(255) NOT NULL COMMENT '主机地址' DEFAULT '', \`oper_location\` varchar(255) NOT NULL COMMENT '操作地点' DEFAULT '', \`operParam\` longtext NOT NULL COMMENT '请求参数', \`jsonResult\` longtext NOT NULL COMMENT '返回参数', \`oper_time\` timestamp(6) NOT NULL COMMENT '操作时间' DEFAULT CURRENT_TIMESTAMP(6), \`status\` char(1) NOT NULL COMMENT '登录状态' DEFAULT '0', \`error_msg\` varchar(2000) NOT NULL COMMENT '错误消息' DEFAULT '', \`cost_time\` int NOT NULL COMMENT '消耗时间' DEFAULT '0', PRIMARY KEY (\`oper_id\`)) ENGINE=InnoDB COMMENT="操作日志记录"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_logininfor\` (\`status\` char(1) NOT NULL COMMENT '状态' DEFAULT '0', \`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`dept_id\` int NULL COMMENT '部门ID', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`info_id\` int NOT NULL AUTO_INCREMENT COMMENT '访问ID', \`user_name\` varchar(50) NOT NULL COMMENT '用户账号' DEFAULT '', \`ipaddr\` varchar(128) NOT NULL COMMENT '登录IP地址' DEFAULT '', \`login_location\` varchar(255) NOT NULL COMMENT '登录地点' DEFAULT '', \`browser\` varchar(50) NOT NULL COMMENT '浏览器类型' DEFAULT '', \`os\` varchar(50) NOT NULL COMMENT '操作系统' DEFAULT '', \`login_time\` timestamp(6) NOT NULL COMMENT '访问时间' DEFAULT CURRENT_TIMESTAMP(6), \`msg\` varchar(255) NOT NULL COMMENT '提示消息' DEFAULT '', PRIMARY KEY (\`info_id\`)) ENGINE=InnoDB COMMENT="系统访问记录"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_job\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`job_id\` int NOT NULL AUTO_INCREMENT COMMENT '任务ID', \`job_name\` varchar(64) NOT NULL COMMENT '任务名称', \`job_group\` varchar(64) NOT NULL COMMENT '任务组名' DEFAULT 'DEFAULT', \`invoke_target\` varchar(500) NOT NULL COMMENT '调用目标字符串', \`cron_expression\` varchar(255) NULL COMMENT 'cron执行表达式', \`misfire_policy\` varchar(20) NULL COMMENT '计划执行错误策略（1立即执行 2执行一次 3放弃执行）' DEFAULT '3', \`status\` char(1) NOT NULL COMMENT '状态' DEFAULT '0', \`dept_id\` int NULL COMMENT '部门ID', PRIMARY KEY (\`job_id\`)) ENGINE=InnoDB COMMENT="定时任务表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`sys_job_log\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`dept_id\` int NULL COMMENT '部门ID', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`job_log_id\` int NOT NULL AUTO_INCREMENT COMMENT '任务日志ID', \`job_name\` varchar(64) NOT NULL COMMENT '任务名称', \`job_group\` varchar(64) NOT NULL COMMENT '任务组名', \`invoke_target\` varchar(500) NOT NULL COMMENT '调用目标字符串', \`job_message\` varchar(500) NULL COMMENT '日志信息', \`status\` char(1) NOT NULL COMMENT '执行状态（0正常 1失败）' DEFAULT '0', \`exception_info\` varchar(2000) NULL COMMENT '异常信息', \`create_time\` datetime(6) NOT NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`job_log_id\`)) ENGINE=InnoDB COMMENT="任务调度日志表"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`goods_craftsmanship\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`craftsmanship_id\` int NOT NULL AUTO_INCREMENT COMMENT '工艺ID', \`name\` varchar(255) NOT NULL COMMENT '名称', \`sort\` int NOT NULL COMMENT '排序' DEFAULT '0', \`description\` varchar(255) NULL COMMENT '描述', \`dept_id\` int NULL COMMENT '部门ID', PRIMARY KEY (\`craftsmanship_id\`)) ENGINE=InnoDB COMMENT="工艺"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`goods_child_craftsmanship\` (\`goods_child_craftsmanship_id\` int NOT NULL AUTO_INCREMENT COMMENT '商品子工艺关联ID', \`name\` varchar(255) NOT NULL COMMENT '名称', \`price\` decimal(10,2) NOT NULL COMMENT '价格' DEFAULT '0.00', \`goods_with_craftsmanship_id\` int NULL COMMENT '商品与工艺关联ID', PRIMARY KEY (\`goods_child_craftsmanship_id\`)) ENGINE=InnoDB COMMENT="商品子工艺关联"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`goods_with_craftsmanship\` (\`goods_with_craftsmanship_id\` int NOT NULL AUTO_INCREMENT COMMENT '商品与工艺关联ID', \`price_type\` enum ('1', '2') NOT NULL COMMENT '价格类型' DEFAULT '1', \`goods_id\` int NULL COMMENT '商品ID', \`craftsmanship_id\` int NULL COMMENT '工艺ID', PRIMARY KEY (\`goods_with_craftsmanship_id\`)) ENGINE=InnoDB COMMENT="商品与工艺关联"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`goods_attrs_options\` (\`goods_attrs_options_id\` int NOT NULL AUTO_INCREMENT COMMENT '商品属性选项ID', \`option_name\` varchar(255) NOT NULL COMMENT '选项名称', \`img_url\` varchar(255) NULL COMMENT '图片URL' DEFAULT '', \`remark\` varchar(255) NULL COMMENT '备注' DEFAULT '', \`price\` decimal(10,2) NULL COMMENT '价格' DEFAULT '0.00', \`num1\` int NULL COMMENT '数值1' DEFAULT '0', \`num2\` int NULL COMMENT '数值2' DEFAULT '0', \`goods_attrs_id\` int NULL COMMENT '商品类目属性ID', PRIMARY KEY (\`goods_attrs_options_id\`)) ENGINE=InnoDB COMMENT="商品属性选项"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`goods_attrs\` (\`goods_class_attrs_id\` int NOT NULL AUTO_INCREMENT COMMENT '商品类目属性ID', \`attr_name\` varchar(255) NOT NULL COMMENT '属性名称', \`join_normal_price\` tinyint NOT NULL COMMENT '是否参与普通价格计算' DEFAULT 1, \`join_square_price\` tinyint NOT NULL COMMENT '是否参与平方价格计算' DEFAULT 1, \`key\` varchar(255) NOT NULL COMMENT '属性键', \`custom_value\` tinyint NOT NULL COMMENT '是否自定义值' DEFAULT 0, \`has_img\` tinyint NOT NULL COMMENT '是否需要图片' DEFAULT 0, \`goods_id\` int NULL COMMENT '商品ID', PRIMARY KEY (\`goods_class_attrs_id\`)) ENGINE=InnoDB COMMENT="商品类目属性"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`goods_sku\` (\`goods_sku_id\` int NOT NULL AUTO_INCREMENT COMMENT 'SKU ID', \`sort_order\` int NOT NULL COMMENT '排序' DEFAULT '0', \`spec_json\` json NOT NULL COMMENT '规格组合 JSON 快照', \`price\` decimal(10,4) NULL COMMENT '价格' DEFAULT '0.0000', \`stock\` int NULL COMMENT '库存' DEFAULT '0', \`spec_fingerprint\` varchar(64) NOT NULL COMMENT '规格指纹（去重）', \`sku_code\` varchar(64) NULL COMMENT '商家编码' DEFAULT '', \`goods_id\` int NULL COMMENT '商品ID', PRIMARY KEY (\`goods_sku_id\`)) ENGINE=InnoDB COMMENT="商品SKU（多规格笛卡尔积的一行）"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`goods_public_supplier\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`goods_public_supplier_id\` int NOT NULL AUTO_INCREMENT COMMENT '公共池商品供应商ID', \`premium_fee\` decimal(10,2) NULL COMMENT '溢价' DEFAULT '0.00', \`dept_id\` int NULL COMMENT '部门ID', \`goods_public_id\` int NULL COMMENT '公共池商品ID', PRIMARY KEY (\`goods_public_supplier_id\`)) ENGINE=InnoDB COMMENT="供应商绑定公共池商品"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`goods_public\` (\`goods_public_id\` int NOT NULL AUTO_INCREMENT COMMENT '公共池商品ID', \`status\` enum ('10', '20', '30') NOT NULL COMMENT '状态' DEFAULT '10', \`remark\` varchar(255) NULL COMMENT '备注' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`audit_time\` datetime NULL COMMENT '审核时间', \`premium_fee\` decimal(10,2) NULL COMMENT '溢价' DEFAULT '0.00', \`goods_id\` int NULL COMMENT '商品ID', UNIQUE INDEX \`REL_1aeec68854ea46d9a3d0749528\` (\`goods_id\`), PRIMARY KEY (\`goods_public_id\`)) ENGINE=InnoDB COMMENT="公共池商品"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`goods\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`goods_id\` int NOT NULL AUTO_INCREMENT COMMENT '商品ID', \`name\` varchar(255) NOT NULL COMMENT '名称', \`description\` varchar(255) NULL COMMENT '描述' DEFAULT '', \`image\` varchar(255) NULL COMMENT '图片' DEFAULT '', \`weight\` decimal(10,2) NULL COMMENT '重量' DEFAULT '0.00', \`volume\` decimal(10,2) NULL COMMENT '体积' DEFAULT '0.00', \`bleed_range\` int NULL COMMENT '图片出血范围（mm）' DEFAULT '0', \`price_type\` enum ('1', '2') NOT NULL COMMENT '计价方式：1-平方计价，2-普通计价' DEFAULT '1', \`shipping_fee\` decimal(10,2) NULL COMMENT '运费' DEFAULT '0.00', \`status\` enum ('10', '20') NOT NULL COMMENT '状态：10-上架中，20-下架' DEFAULT '10', \`shipping_address\` varchar(255) NULL COMMENT '发货地址' DEFAULT '', \`shipping_type\` enum ('1', '2') NOT NULL COMMENT '运费类型 1-固定运费， 2-运费模板' DEFAULT '2', \`shipping_template_ids\` json NULL COMMENT '快递模板ids', \`base_packing_fee\` decimal(10,2) NULL COMMENT '基础打包费用' DEFAULT '0.00', \`is_customization\` tinyint NOT NULL COMMENT '是否定制商品' DEFAULT 0, \`show_price\` decimal(10,2) NULL COMMENT '展示价格' DEFAULT '0.00', \`upload_type\` enum ('card', 'photo', 'roll') NOT NULL COMMENT '上传类型(card:卡片,photo:照片,roll:条幅)' DEFAULT 'card', \`category_id\` int NULL COMMENT '分类ID', \`class_id\` int NULL COMMENT '类目ID', \`dept_id\` int NULL COMMENT '部门ID', PRIMARY KEY (\`goods_id\`)) ENGINE=InnoDB COMMENT="商品"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`goods_category\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`category_id\` int NOT NULL AUTO_INCREMENT COMMENT '分类ID', \`name\` varchar(255) NOT NULL COMMENT '名称', \`parent_id\` int NULL COMMENT '父ID', \`sort\` int NOT NULL COMMENT '排序' DEFAULT '0', \`icon\` varchar(255) NULL COMMENT '图标', \`description\` varchar(255) NULL COMMENT '描述', \`status\` char NOT NULL COMMENT '状态' DEFAULT '1', \`dept_id\` int NULL COMMENT '部门ID', PRIMARY KEY (\`category_id\`)) ENGINE=InnoDB COMMENT="商品分类"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`goods_class\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`class_id\` int NOT NULL AUTO_INCREMENT COMMENT '类目ID', \`name\` varchar(255) NOT NULL COMMENT '名称', \`parent_id\` int NOT NULL COMMENT '父ID' DEFAULT '0', \`sort\` int NOT NULL COMMENT '排序' DEFAULT '0', \`dept_id\` int NULL COMMENT '部门ID', \`type\` enum ('1', '2') NOT NULL COMMENT '类目类型：1-定制性商品，2-非定制型商品' DEFAULT '1', \`status\` char NOT NULL COMMENT '状态' DEFAULT '1', \`description\` varchar(255) NULL COMMENT '描述', \`attr_text\` varchar(255) NULL COMMENT '属性文本', PRIMARY KEY (\`class_id\`)) ENGINE=InnoDB COMMENT="商品类目"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`goods_class_attrs\` (\`attr_id\` int NOT NULL AUTO_INCREMENT COMMENT '属性ID', \`attr_name\` varchar(255) NOT NULL COMMENT '属性名称', \`join_normal_price\` tinyint NOT NULL COMMENT '是否参与普通价格计算' DEFAULT 1, \`enable\` tinyint NOT NULL COMMENT '是否启用' DEFAULT 1, \`key\` varchar(255) NOT NULL COMMENT '属性键', \`join_square_price\` tinyint NOT NULL COMMENT '是否参与平方价格计算' DEFAULT 1, \`class_id\` int NULL COMMENT '类目ID', PRIMARY KEY (\`attr_id\`)) ENGINE=InnoDB COMMENT="类目属性"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_goods\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`id\` int NOT NULL AUTO_INCREMENT COMMENT 'ID', \`created_at\` datetime NULL COMMENT '创建时间', \`goods_id\` int NULL COMMENT '电商平台商品ID' DEFAULT '0', \`goods_name\` varchar(255) NULL COMMENT '商品名称' DEFAULT '', \`goods_quantity\` int NULL COMMENT '商品数量' DEFAULT '0', \`goods_reserve_quantity\` int NULL COMMENT '商品预留数量' DEFAULT '0', \`image_url\` varchar(255) NULL COMMENT '商品图片URL' DEFAULT '', \`is_more_sku\` tinyint NULL COMMENT '是否有多SKU' DEFAULT 0, \`is_onsale\` tinyint NULL COMMENT '是否上架' DEFAULT 0, \`outer_goods_id\` varchar(255) NULL COMMENT '外部商品ID' DEFAULT '', \`thumb_url\` varchar(255) NULL COMMENT '商品缩略图URL' DEFAULT '', \`mid\` int NULL COMMENT 'MID' DEFAULT '0', \`dept_id\` int NULL COMMENT '部门ID' DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB COMMENT="电商平台商品"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_sku\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'ID', \`is_sku_onsale\` tinyint NULL COMMENT '是否上架' DEFAULT 0, \`outer_id\` varchar(255) NULL COMMENT '外部ID' DEFAULT '', \`reserve_quantity\` int NULL COMMENT '预留数量' DEFAULT '0', \`sku_id\` int NULL COMMENT 'SKU ID' DEFAULT '0', \`sku_quantity\` int NULL COMMENT 'SKU数量' DEFAULT '0', \`spec\` varchar(255) NULL COMMENT '规格' DEFAULT '', \`goods_id\` int NULL COMMENT 'ID', PRIMARY KEY (\`id\`)) ENGINE=InnoDB COMMENT="电商平台SKU"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_spec\` (\`id\` int NOT NULL AUTO_INCREMENT COMMENT 'ID', \`parent_id\` int NULL COMMENT '父ID' DEFAULT '0', \`parent_name\` varchar(255) NULL COMMENT '父名称' DEFAULT '', \`spec_id\` int NULL COMMENT '规格ID' DEFAULT '0', \`spec_name\` varchar(255) NULL COMMENT '规格名称' DEFAULT '', \`spec_note\` varchar(255) NULL COMMENT '规格备注' DEFAULT '', \`sku_id\` int NULL COMMENT 'ID', PRIMARY KEY (\`id\`)) ENGINE=InnoDB COMMENT="电商平台规格"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_shop\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`shop_id\` int NOT NULL AUTO_INCREMENT COMMENT '店铺ID', \`shop_name\` varchar(255) NULL COMMENT '店铺名称' DEFAULT '', \`platform_type\` enum ('100', '200', '300', '400', '500') NOT NULL COMMENT '平台类型', \`token\` varchar(255) NULL COMMENT 'token' DEFAULT '', \`mid\` int NULL COMMENT 'mid', \`expires_time\` datetime NULL COMMENT 'token过期时间', \`user_name\` varchar(255) NULL COMMENT '用户名' DEFAULT '', \`mall_id\` int NULL COMMENT '商城ID', \`shop_code\` varchar(255) NULL COMMENT '店铺编码' DEFAULT '', \`dept_id\` int NULL COMMENT '部门ID', PRIMARY KEY (\`shop_id\`)) ENGINE=InnoDB COMMENT="电商平台店铺"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_refund\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`id\` int NOT NULL AUTO_INCREMENT COMMENT '售后ID', \`after_sale_reason\` varchar(255) NULL COMMENT '售后原因' DEFAULT '', \`after_sales_status\` int NULL COMMENT '售后状态' DEFAULT '0', \`after_sales_type\` int NULL COMMENT '售后类型' DEFAULT '0', \`confirm_time\` datetime NULL COMMENT '确认时间', \`created_time\` datetime NULL COMMENT '创建时间', \`discount_amount\` decimal(10,2) NULL COMMENT '优惠金额' DEFAULT '0.00', \`dispute_refund_status\` int NULL COMMENT '争议退款状态' DEFAULT '0', \`good_image\` varchar(255) NULL COMMENT '商品图片' DEFAULT '', \`goods_id\` bigint NULL COMMENT '商品ID' DEFAULT '0', \`goods_name\` varchar(255) NULL COMMENT '商品名称' DEFAULT '', \`goods_number\` int NULL COMMENT '商品数量' DEFAULT '0', \`goods_price\` decimal(10,2) NULL COMMENT '商品价格' DEFAULT '0.00', \`platform_after_sales_id\` int NULL COMMENT '平台售后ID' DEFAULT '0', \`order_amount\` decimal(10,2) NULL COMMENT '订单金额' DEFAULT '0.00', \`order_sn\` varchar(255) NULL COMMENT '订单号' DEFAULT '', \`outer_goods_id\` varchar(255) NULL COMMENT '外部商品ID' DEFAULT '', \`outer_id\` varchar(255) NULL COMMENT '外部ID' DEFAULT '', \`refund_amount\` decimal(10,2) NULL COMMENT '退款金额' DEFAULT '0.00', \`refund_operator_role\` int NULL COMMENT '退款操作人角色' DEFAULT '0', \`shipping_name\` varchar(255) NULL COMMENT '物流公司名称' DEFAULT '', \`sku_id\` varchar(50) NULL COMMENT 'SKU ID' DEFAULT '', \`speed_refund_flag\` int NULL COMMENT '极速退款标记' DEFAULT '0', \`speed_refund_status\` varchar(50) NULL COMMENT '极速退款状态' DEFAULT '', \`tracking_number\` varchar(50) NULL COMMENT '物流单号' DEFAULT '', \`updated_time\` datetime NULL COMMENT '更新时间', \`user_shipping_status\` varchar(10) NULL COMMENT '用户寄件状态' DEFAULT '', \`mid\` int NULL COMMENT 'MID' DEFAULT '0', \`dept_id\` int NULL COMMENT '部门ID' DEFAULT '0', PRIMARY KEY (\`id\`)) ENGINE=InnoDB COMMENT="电商平台售后"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_order_goodsInfo\` (\`pt_order_goods_info_id\` int NOT NULL AUTO_INCREMENT COMMENT '订单商品信息ID', \`goods_count\` int NULL COMMENT '商品数量' DEFAULT '0', \`goods_name\` varchar(255) NULL COMMENT '商品名称' DEFAULT '', \`goods_img\` varchar(255) NULL COMMENT '商品图片' DEFAULT '', \`goods_spec\` varchar(255) NULL COMMENT '商品规格' DEFAULT '', \`goods_price\` decimal(10,2) NULL COMMENT '商品价格' DEFAULT '0.00', \`goods_id\` varchar(255) NULL COMMENT '商品ID' DEFAULT '', \`sku_id\` varchar(255) NULL COMMENT 'SKU ID' DEFAULT '', \`outer_id\` varchar(255) NULL COMMENT '外部ID' DEFAULT '', \`outer_goods_id\` varchar(255) NULL COMMENT '外部商品ID' DEFAULT '', \`ptOrderPtOrderId\` int NULL COMMENT '订单ID', PRIMARY KEY (\`pt_order_goods_info_id\`)) ENGINE=InnoDB COMMENT="电商平台订单商品信息"`,
    );
    await queryRunner.query(
      `CREATE TABLE \`e_commerce_platform_order\` (\`tenant_id\` int NOT NULL COMMENT '租户ID' DEFAULT '1', \`owner_user_id\` int NULL COMMENT '数据所有者用户ID', \`create_by\` varchar(64) NOT NULL COMMENT '创建者' DEFAULT '', \`create_time\` datetime(6) NULL COMMENT '创建时间' DEFAULT CURRENT_TIMESTAMP(6), \`update_by\` varchar(64) NOT NULL COMMENT '更新者' DEFAULT '', \`update_time\` datetime(6) NULL COMMENT '更新时间' DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), \`delete_time\` datetime(6) NULL COMMENT '删除时间', \`pt_order_id\` int NOT NULL AUTO_INCREMENT COMMENT '订单ID', \`receiver_name\` varchar(255) NULL COMMENT '收货人姓名' DEFAULT '', \`receiver_phone\` varchar(255) NULL COMMENT '收货人电话' DEFAULT '', \`province\` varchar(255) NULL COMMENT '省份' DEFAULT '', \`city\` varchar(255) NULL COMMENT '城市' DEFAULT '', \`town\` varchar(255) NULL COMMENT '乡镇' DEFAULT '', \`receiver_address\` varchar(255) NULL COMMENT '收货人地址' DEFAULT '', \`order_sn\` varchar(255) NULL COMMENT '订单号' DEFAULT '', \`goods_name\` varchar(255) NULL COMMENT '商品名称' DEFAULT '', \`goods_img\` varchar(255) NULL COMMENT '商品图片' DEFAULT '', \`goods_spec\` varchar(255) NULL COMMENT '商品规格' DEFAULT '', \`goods_price\` decimal(10,2) NULL COMMENT '商品价格' DEFAULT '0.00', \`goods_id\` varchar(255) NULL COMMENT '商品ID' DEFAULT '', \`sku_id\` varchar(255) NULL COMMENT 'SKU ID' DEFAULT '', \`is_pre_sale\` tinyint NULL COMMENT '是否预售' DEFAULT 0, \`last_ship_time\` datetime NULL COMMENT '最后发货时间', \`confirm_time\` datetime NULL COMMENT '确认时间', \`remark\` varchar(255) NULL COMMENT '备注' DEFAULT '', \`goods_count\` int NULL COMMENT '商品数量' DEFAULT '0', \`pay_amount\` decimal(10,2) NULL COMMENT '支付金额' DEFAULT '0.00', \`order_status\` enum ('1', '2', '3', '5') NULL COMMENT '订单状态' DEFAULT '1', \`refund_status\` enum ('1', '2', '3', '4', '5') NULL COMMENT '退款状态' DEFAULT '1', \`remark_tag\` int NULL COMMENT '备注标签' DEFAULT '0', \`remark_tag_name\` varchar(255) NULL COMMENT '备注标签名称' DEFAULT '', \`receiver_name_encrypt\` varchar(255) NULL COMMENT '收货人姓名加密' DEFAULT '', \`receiver_phone_encrypt\` varchar(255) NULL COMMENT '收货人电话加密' DEFAULT '', \`receiver_address_encrypt\` varchar(255) NULL COMMENT '收货人地址加密' DEFAULT '', \`open_address_id\` varchar(255) NULL COMMENT '开户地址ID' DEFAULT '', \`open_address_id_2\` varchar(255) NULL COMMENT '开户地址ID2' DEFAULT '', \`town_id\` int NULL COMMENT '乡镇ID' DEFAULT '0', \`outer_id\` varchar(255) NULL COMMENT '外部ID' DEFAULT '', \`outer_goods_id\` varchar(255) NULL COMMENT '外部商品ID' DEFAULT '', \`mid\` int NULL COMMENT 'MID' DEFAULT '0', \`dept_id\` int NULL COMMENT '部门ID' DEFAULT '0', PRIMARY KEY (\`pt_order_id\`)) ENGINE=InnoDB COMMENT="电商平台订单"`,
    );
    await queryRunner.query(
      `ALTER TABLE \`sys_shipping_template_rule\` ADD CONSTRAINT \`FK_38c983ba936c86bea0cd0407a82\` FOREIGN KEY (\`shipping_template_id\`) REFERENCES \`sys_shipping_template\`(\`shipping_template_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`sys_shipping_template\` ADD CONSTRAINT \`FK_86297801189dcf7f639c5e69a1a\` FOREIGN KEY (\`express_id\`) REFERENCES \`sys_express\`(\`express_id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`goods_child_craftsmanship\` ADD CONSTRAINT \`FK_aeb39411588c68adfaf545653b8\` FOREIGN KEY (\`goods_with_craftsmanship_id\`) REFERENCES \`goods_with_craftsmanship\`(\`goods_with_craftsmanship_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`goods_with_craftsmanship\` ADD CONSTRAINT \`FK_7d83f83f001d40dbdd17ab058d3\` FOREIGN KEY (\`goods_id\`) REFERENCES \`goods\`(\`goods_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`goods_with_craftsmanship\` ADD CONSTRAINT \`FK_e39e27a81e3418c79fcd1fd08ed\` FOREIGN KEY (\`craftsmanship_id\`) REFERENCES \`goods_craftsmanship\`(\`craftsmanship_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`goods_attrs_options\` ADD CONSTRAINT \`FK_5932ebf34f05eea00a2aea866bd\` FOREIGN KEY (\`goods_attrs_id\`) REFERENCES \`goods_attrs\`(\`goods_class_attrs_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`goods_attrs\` ADD CONSTRAINT \`FK_13d3721e494a558faf54ffd9e88\` FOREIGN KEY (\`goods_id\`) REFERENCES \`goods\`(\`goods_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`goods_sku\` ADD CONSTRAINT \`FK_26973dc554d13fe8aafdbd45e7c\` FOREIGN KEY (\`goods_id\`) REFERENCES \`goods\`(\`goods_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`goods_public_supplier\` ADD CONSTRAINT \`FK_fdb292916bb78a75671f9596a0f\` FOREIGN KEY (\`goods_public_id\`) REFERENCES \`goods_public\`(\`goods_public_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`goods_public\` ADD CONSTRAINT \`FK_1aeec68854ea46d9a3d07495280\` FOREIGN KEY (\`goods_id\`) REFERENCES \`goods\`(\`goods_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`goods_class_attrs\` ADD CONSTRAINT \`FK_bba60b76a8176f48f340bcfd3e3\` FOREIGN KEY (\`class_id\`) REFERENCES \`goods_class\`(\`class_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`e_commerce_platform_sku\` ADD CONSTRAINT \`FK_3b35d982aa8bbae4afce973508e\` FOREIGN KEY (\`goods_id\`) REFERENCES \`e_commerce_platform_goods\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`e_commerce_platform_spec\` ADD CONSTRAINT \`FK_298068f6a1a25ef0b81fdc65a20\` FOREIGN KEY (\`sku_id\`) REFERENCES \`e_commerce_platform_sku\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
    await queryRunner.query(
      `ALTER TABLE \`e_commerce_platform_order_goodsInfo\` ADD CONSTRAINT \`FK_deb30e13848004b8855fe97b501\` FOREIGN KEY (\`ptOrderPtOrderId\`) REFERENCES \`e_commerce_platform_order\`(\`pt_order_id\`) ON DELETE CASCADE ON UPDATE NO ACTION`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(`ALTER TABLE \`e_commerce_platform_order_goodsInfo\` DROP FOREIGN KEY \`FK_deb30e13848004b8855fe97b501\``);
    await queryRunner.query(`ALTER TABLE \`e_commerce_platform_spec\` DROP FOREIGN KEY \`FK_298068f6a1a25ef0b81fdc65a20\``);
    await queryRunner.query(`ALTER TABLE \`e_commerce_platform_sku\` DROP FOREIGN KEY \`FK_3b35d982aa8bbae4afce973508e\``);
    await queryRunner.query(`ALTER TABLE \`goods_class_attrs\` DROP FOREIGN KEY \`FK_bba60b76a8176f48f340bcfd3e3\``);
    await queryRunner.query(`ALTER TABLE \`goods_public\` DROP FOREIGN KEY \`FK_1aeec68854ea46d9a3d07495280\``);
    await queryRunner.query(`ALTER TABLE \`goods_public_supplier\` DROP FOREIGN KEY \`FK_fdb292916bb78a75671f9596a0f\``);
    await queryRunner.query(`ALTER TABLE \`goods_sku\` DROP FOREIGN KEY \`FK_26973dc554d13fe8aafdbd45e7c\``);
    await queryRunner.query(`ALTER TABLE \`goods_attrs\` DROP FOREIGN KEY \`FK_13d3721e494a558faf54ffd9e88\``);
    await queryRunner.query(`ALTER TABLE \`goods_attrs_options\` DROP FOREIGN KEY \`FK_5932ebf34f05eea00a2aea866bd\``);
    await queryRunner.query(`ALTER TABLE \`goods_with_craftsmanship\` DROP FOREIGN KEY \`FK_e39e27a81e3418c79fcd1fd08ed\``);
    await queryRunner.query(`ALTER TABLE \`goods_with_craftsmanship\` DROP FOREIGN KEY \`FK_7d83f83f001d40dbdd17ab058d3\``);
    await queryRunner.query(`ALTER TABLE \`goods_child_craftsmanship\` DROP FOREIGN KEY \`FK_aeb39411588c68adfaf545653b8\``);
    await queryRunner.query(`ALTER TABLE \`sys_shipping_template\` DROP FOREIGN KEY \`FK_86297801189dcf7f639c5e69a1a\``);
    await queryRunner.query(`ALTER TABLE \`sys_shipping_template_rule\` DROP FOREIGN KEY \`FK_38c983ba936c86bea0cd0407a82\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_order\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_order_goodsInfo\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_refund\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_shop\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_spec\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_sku\``);
    await queryRunner.query(`DROP TABLE \`e_commerce_platform_goods\``);
    await queryRunner.query(`DROP TABLE \`goods_class_attrs\``);
    await queryRunner.query(`DROP TABLE \`goods_class\``);
    await queryRunner.query(`DROP TABLE \`goods_category\``);
    await queryRunner.query(`DROP TABLE \`goods\``);
    await queryRunner.query(`DROP INDEX \`REL_1aeec68854ea46d9a3d0749528\` ON \`goods_public\``);
    await queryRunner.query(`DROP TABLE \`goods_public\``);
    await queryRunner.query(`DROP TABLE \`goods_public_supplier\``);
    await queryRunner.query(`DROP TABLE \`goods_sku\``);
    await queryRunner.query(`DROP TABLE \`goods_attrs\``);
    await queryRunner.query(`DROP TABLE \`goods_attrs_options\``);
    await queryRunner.query(`DROP TABLE \`goods_with_craftsmanship\``);
    await queryRunner.query(`DROP TABLE \`goods_child_craftsmanship\``);
    await queryRunner.query(`DROP TABLE \`goods_craftsmanship\``);
    await queryRunner.query(`DROP TABLE \`sys_job_log\``);
    await queryRunner.query(`DROP TABLE \`sys_job\``);
    await queryRunner.query(`DROP TABLE \`sys_logininfor\``);
    await queryRunner.query(`DROP TABLE \`sys_oper_log\``);
    await queryRunner.query(`DROP TABLE \`sys_config\``);
    await queryRunner.query(`DROP TABLE \`sys_dept\``);
    await queryRunner.query(`DROP INDEX \`IDX_f4e4273658733a3bbe6a2479bf\` ON \`sys_dict_type\``);
    await queryRunner.query(`DROP TABLE \`sys_dict_type\``);
    await queryRunner.query(`DROP TABLE \`sys_dict_data\``);
    await queryRunner.query(`DROP TABLE \`sys_menu\``);
    await queryRunner.query(`DROP TABLE \`sys_notice\``);
    await queryRunner.query(`DROP TABLE \`sys_post\``);
    await queryRunner.query(`DROP TABLE \`sys_region\``);
    await queryRunner.query(`DROP TABLE \`sys_role_menu\``);
    await queryRunner.query(`DROP TABLE \`sys_role_dept\``);
    await queryRunner.query(`DROP TABLE \`sys_role\``);
    await queryRunner.query(`DROP TABLE \`sys_shipping_template\``);
    await queryRunner.query(`DROP TABLE \`sys_shipping_template_rule\``);
    await queryRunner.query(`DROP TABLE \`sys_express\``);
    await queryRunner.query(`DROP TABLE \`gen_table_column\``);
    await queryRunner.query(`DROP TABLE \`sys_user_post\``);
    await queryRunner.query(`DROP TABLE \`gen_table\``);
    await queryRunner.query(`DROP TABLE \`sys_user\``);
    await queryRunner.query(`DROP TABLE \`sys_user_role\``);
    await queryRunner.query(`DROP TABLE \`sys_upload\``);
  }
}
